#!/bin/bash

_start(){
    if [[ ! $1 || $1 == "--help" ]]; then
        echo -e "\e[33mUsage:\e[39m docker-host start [CONFIG_ENV_DIR]\n"
        echo -e "\e[33mOptions variables:\e[39m"
        echo -e " name\t\texample"
        echo -e " \e[32mBASE_DIR\e[39m\t~"
        echo -e " \e[32mCONFIGS_DIR\e[39m\t~/Configs"
        echo -e " \e[32mCONFIG_DIR\e[39m\t~/Configs/hello"
        echo -e " \e[32mCONFIG_ENV_DIR\e[39m\t~/Configs/hello/dev"
        echo -e " \e[32mDATA_DIR\e[39m\t~/Data/hello"
        echo -e " \e[32mDATA_ENV_DIR\e[39m\t~/Data/hello/dev"
        echo -e " \e[32mPROJECTS_DIR\e[39m\t~/Projects"
        echo -e " \e[32mCONFIG\e[39m\t\thello"
        echo -e " \e[32mENV\e[39m\t\tdev"
        exit
    fi
    CONFIG_ENV_DIR=$(readlink -e $1)
    CONFIG_DIR=$(readlink -e ${CONFIG_ENV_DIR}/..)
    CONFIGS_DIR=$(readlink -e ${CONFIG_DIR}/..)
    BASE_DIR=$(readlink -e ${CONFIGS_DIR}/..)
    CONFIG=${CONFIG_DIR//${CONFIGS_DIR}/}
    CONFIG=${CONFIG:1}
    ENV=${CONFIG_ENV_DIR//${CONFIG_DIR}/}
    ENV=${ENV:1}
    DATA_DIR=$(readlink -e ${BASE_DIR}/Data/${CONFIG})
    DATA_ENV_DIR=$(readlink -e ${DATA_DIR}/${ENV})
    PROJECTS_DIR=$(readlink -e ${BASE_DIR}/Projects)
    _RUNFILE=${CONFIG_ENV_DIR}/.run
    if [ ! -f ${_RUNFILE} ]; then
        echo -e "\e[31mRun file not found\e[39m"
        exit
    fi
    echo -e "\e[32mKilling containers\e[39m"
    docker kill $(docker ps -q) &> /dev/null
    echo -e "\e[32mRemoving containers\e[39m"
    docker rm $(docker ps -qa) &> /dev/null
    _add_optionsfile(){
        local _OPTIONSFILE=$1
        if [ -f ${_OPTIONSFILE} ]; then
            while read _OPTION
            do
                if [ ${_OPTION:0:1} != '#' ]; then
                    _OPTIONS+=${_OPTION}' '
                fi
            done <${_OPTIONSFILE}
        fi
    }
    _start_imagebuild(){
        local _IMAGEFILE=$1
        local _P_IMAGE=$(head -n 1 ${_IMAGEFILE})
        local _P_IMAGE=${_P_IMAGE//FROM /}
        local _P_IMAGEDIR=${CONFIGS_DIR}/${_P_IMAGE//_//}
        local _P_IMAGEFILE=${_P_IMAGEDIR}/Dockerfile
        if [ ! -f ${_P_IMAGEFILE} ]; then
            return
        fi
        _add_optionsfile ${_P_IMAGEDIR}/.globaloptions
        _start_imagebuild ${_P_IMAGEFILE}
        echo -e "\e[32mBuilding parent image ${_P_IMAGE}\e[39m"
        docker build -t ${_P_IMAGE} ${_P_IMAGEDIR} 2> /dev/null
    }
    for _CONTAINERPATH in $(cat ${_RUNFILE}); do
        _CONTAINERDIR=${CONFIG_ENV_DIR}/${_CONTAINERPATH}
        for _IMAGEFILE in $(find ${_CONTAINERDIR} -name Dockerfile); do
            _CONTAINER=${_IMAGEFILE//${CONFIG_ENV_DIR}/}
            _CONTAINER=${_CONTAINER:1:-11}
            _CONTAINER=${_CONTAINER////_}
            _IMAGE=${CONFIG}/${ENV}_${_CONTAINER}
            _IMAGEDIR=$(dirname ${_IMAGEFILE})
            _OPTIONS=''
            _start_imagebuild ${_IMAGEFILE}
            echo -e "\e[32mBuilding image ${_IMAGE}\e[39m"
            docker build -t ${_IMAGE} ${_IMAGEDIR} 2> /dev/null
            _add_optionsfile ${_IMAGEDIR}/.globaloptions
            _add_optionsfile ${_IMAGEDIR}/.options
            _OPTIONS=$(eval echo ${_OPTIONS})
            echo -e "\e[32mRunning container ${_CONTAINER}\e[39m"
            docker run -h ${_CONTAINER} --name ${_CONTAINER} ${_OPTIONS} -tid ${_IMAGE} 1> /dev/null
        done
    done
}

_stop(){
    docker kill $(docker ps -q) &> /dev/null
    docker rm $(docker ps -aq) &> /dev/null
}

_status(){
    echo -e "\e[32mIMAGES\e[39m"
    docker images
    echo -e "\n\e[32mCONTAINERS\e[39m"
    docker ps -a
}

_clean(){
    docker rm -f $(docker ps -aq -f status=exited) &> /dev/null
    docker rmi -f $(docker images | grep "^<none>" | awk "{print \$3}") &> /dev/null
}

_clear(){
    if [[ $1 == "--help" ]]; then
        echo -e "\e[33mUsage:\e[39m docker-host clear [IMAGE_PATTERN]"
        exit
    fi
    docker kill $(docker ps -q) &> /dev/null
    docker rm $(docker ps -aq) &> /dev/null
    _IMAGES=$(docker images -q)
    if [[ $1 ]]; then
        _IMAGES=$(docker images | grep $1 | awk "{print \$3}")
    fi
    docker rmi -f ${_IMAGES} &> /dev/null
}

_export(){
    if [[ ! $1 || $1 == "--help" ]]; then
        echo -e "\e[33mUsage:\e[39m docker-host export [CONFIG_DIR]\n"
        echo -e "\e[33mInformation:\e[39m The paths are relative to home directory."
        exit
    fi
    _CONFIG_DIR=$(readlink -e $1)
    for _FILE in $(find ${_CONFIG_DIR}/.export -type f); do
        _HOST=${_FILE##*/}
        echo -e "\e[32mExporting on ${_HOST}\e[39m"
        _SOURCES=''
        _EXCLUDES=''
        for _PATH in $(cat ${_FILE}); do
            if [ ${_PATH:0:1} != '#' ]; then
                if [ ${_PATH:0:1} == '!' ]; then
                    _EXCLUDES+='--exclude '${_PATH:1}' '
                else
                    _SOURCES+=${_PATH}' '
                fi
            fi
        done
        cd && rsync ${_EXCLUDES}--delete --delete-excluded -avzRe ssh ${_SOURCES} ${_HOST}:~
    done
}

_import(){
    if [[ ! $1 || $1 == "--help" ]]; then
        echo -e "\e[33mUsage:\e[39m docker-host import [CONFIG_DIR]\n"
        echo -e "\e[33mInformation:\e[39m The paths are relative to home directory."
        exit
    fi
    _CONFIG_DIR=$(readlink -e $1)
    for _FILE in $(find ${_CONFIG_DIR}/.import -type f); do
        _HOST=${_FILE##*/}
        echo -e "\e[32mImporting from ${_HOST}\e[39m"
        _SOURCES=''
        _EXCLUDES=''
        for _PATH in $(cat ${_FILE}); do
            if [ ${_PATH:0:1} != '#' ]; then
                if [ ${_PATH:0:1} == '!' ]; then
                    _EXCLUDES+='--exclude '${_PATH:1}' '
                else
                    _SOURCES+=${_HOST}:${_PATH}' '
                fi
            fi
        done
        rsync ${_EXCLUDES}--delete --delete-excluded -avzRe ssh ${_SOURCES} ~
    done
}

_login(){
    if [[ ! $1 || $1 == "--help" ]]; then
        echo -e "\e[33mUsage:\e[39m docker-host login ([USER]@)[CONTAINER]\n"
        echo -e "\e[33mInformation:\e[39m The username is root by default."
        exit
    fi
    _CONTAINER=$1
    _USER=root
    _TMP=(${_CONTAINER//@/ })
    if [ ${_TMP[1]} ]; then
        _CONTAINER=${_TMP[1]}
        _USER=${_TMP[0]}
    fi
    docker exec -ti ${_CONTAINER} setuser ${_USER} bash
}

_update(){
    cd /usr/local/bin
    sudo wget -N https://raw.githubusercontent.com/softilabs/docker-host/master/docker-host
    sudo chmod +x docker-host
}

_usage(){
    echo -e "     _            _                   _               _   "
    echo -e "  __| | ___   ___| | _____ _ __      | |__   ___  ___| |_ "
    echo -e " / _  |/ _ \ / __| |/ / _ \ '__| ___ | '_ \ / _ \/ __| __|"
    echo -e "( (_) | (_) | (__|   <  __/ |   |___|| | | | (_) \__ \ |_ "
    echo -e " \__,_|\___/ \___|_|\_\___|_|        |_| |_|\___/|___/\__|"
    echo -e "                                                          "
    echo -e "A Docker extension to manage multiple containers and more\n"
    echo -e "\e[33mUsage:\e[39m docker-host [COMMAND]\n"
    echo -e "\e[33mCommands:\e[39m"
    echo -e " \e[32mstart\e[39m\t\tStart a configuration"
    echo -e " \e[32mstop\e[39m\t\tStop all containers"
    echo -e " \e[32mstatus\e[39m\t\tList all images and all containers"
    echo -e " \e[32mclean\e[39m\t\tDelete exited containers and unused images"
    echo -e " \e[32mclear\e[39m\t\tDelete all containers and all images"
    echo -e " \e[32mexport\e[39m\t\tExport data to remote host(s)"
    echo -e " \e[32mimport\e[39m\t\tImport data to remote host(s)"
    echo -e " \e[32mlogin\e[39m\t\tOpen a bash terminal on a running container"
    echo -e " \e[32mupdate\e[39m\t\tUpdate from GitHub"
}

case $1 in
    start) _start $2 ;;
    stop) _stop ;;
    status) _status ;;
    clean) _clean ;;
    clear) _clear $2 ;;
    export) _export $2 ;;
    import) _import $2 ;;
    login) _login $2 ;;
    update) _update $2 ;;
    *) _usage ;;
esac
